build-idx:
  generated-by: csolution version 2.8.0
  csolution: application_n5x.csolution.yml
  tmpdir: tmp
  cprojects:
    - cproject: application_n5x.cproject.yml
  cbuilds:
    - cbuild: application_n5x+xiao_nRF52840.cbuild.yml
      project: application_n5x
      configuration: +xiao_nRF52840
      messages:
        info:
          - application_n5x.cbuild-pack.yml - file is already up-to-date
          - application_n5x+xiao_nRF52840.cbuild-run.yml - file is already up-to-date
          - application_n5x+xiao_nRF52840.cbuild.yml - file is already up-to-date
      packs-unused:
        - pack: ARM::CMSIS-DSP@1.16.2
        - pack: ARM::CMSIS-NN@4.1.0
