cbuild-pack:
  resolved-packs:
    - resolved-pack: ARM::CMSIS@6.1.0
      selected-by-pack:
        - ARM::CMSIS@^6.1.0
    - resolved-pack: ARM::CMSIS-DSP@1.16.2
      selected-by-pack:
        - ARM::CMSIS-DSP@^1.10.1
    - resolved-pack: ARM::CMSIS-NN@4.1.0
      selected-by-pack:
        - ARM::CMSIS-NN@^4.0.0
    - resolved-pack: NordicSemiconductor::nRF_DeviceFamilyPack@8.44.1
      selected-by-pack:
        - NordicSemiconductor::nRF_DeviceFamilyPack@^8.44.1
