cbuild-run:
  generated-by: csolution version 2.8.0
  solution: application_n5x.csolution.yml
  target-type: xiao_nRF52840
  compiler: AC6
  device: Nordic Semiconductor::nRF52840_xxAA
  device-pack: NordicSemiconductor::nRF_DeviceFamilyPack@8.44.1
  programming:
    - algorithm: ${CMSIS_PACK_ROOT}/NordicSemiconductor/nRF_DeviceFamilyPack/8.44.1/Flash/nrf52xxx.flm
      start: 0x00000000
      size: 0x00200000
      ram-start: 0x20000000
      ram-size: 0x00004000
      default: true
    - algorithm: ${CMSIS_PACK_ROOT}/NordicSemiconductor/nRF_DeviceFamilyPack/8.44.1/Flash/nrf52xxx_uicr.flm
      start: 0x10001000
      size: 0x00001000
      ram-start: 0x20000000
      ram-size: 0x00004000
      default: true
    - algorithm: ${CMSIS_PACK_ROOT}/NordicSemiconductor/nRF_DeviceFamilyPack/8.44.1/Flash/nrf52xxx_sde.flm
      start: 0x00000000
      size: 0x00200000
      ram-start: 0x20000000
      ram-size: 0x00004000
  system-descriptions:
    - file: ${CMSIS_PACK_ROOT}/NordicSemiconductor/nRF_DeviceFamilyPack/8.44.1/SVD/nrf52840.svd
      type: svd
  output:
    - file: out/application_n5x/xiao_nRF52840/application_n5x.bin
      info: generate by application_n5x+xiao_nRF52840
      type: bin
    - file: out/application_n5x/xiao_nRF52840/application_n5x.axf
      info: generate by application_n5x+xiao_nRF52840
      type: elf
    - file: out/application_n5x/xiao_nRF52840/application_n5x.hex
      info: generate by application_n5x+xiao_nRF52840
      type: hex
  system-resources:
    memory:
      - name: IROM1
        start: 0x00000000
        size: 0x00100000
        default: true
        startup: true
        from-pack: NordicSemiconductor::nRF_DeviceFamilyPack@8.44.1
      - name: IROM2
        start: 0x12000000
        size: 0x08000000
        default: true
        from-pack: NordicSemiconductor::nRF_DeviceFamilyPack@8.44.1
      - name: IRAM1
        start: 0x20000000
        size: 0x00040000
        default: true
        from-pack: NordicSemiconductor::nRF_DeviceFamilyPack@8.44.1
      - name: IRAM2
        start: 0x00800000
        size: 0x00040000
        default: true
        from-pack: NordicSemiconductor::nRF_DeviceFamilyPack@8.44.1
  debugger:
    - name: <default>
      port: swd
      clock: 10000000
      dbgconf: ../../../../../../../../../../../../../..
